### ISSUE TITLE
Injected data

### ISSUE THREAD

**Issue by CrankyDad** [inspired-technologies/signalk-openweather-plugin#11]
Just a very small comment/question. 
The documentation states that there are data put under the environment.forecast.time.*

But there is only one data point injected at environment.forecast.time and it's not clear what that date/time refers to.

Is it the time for when the forecast is valid (i.e. the data retrieved will be the status at that time), or is it when there will be a new forecast collected (the forecast is valid to this date/time and new one will be fetched)?

Also, I've not got my head around the "Forecast offset to localtime parameter".  Would that be when the next forecast is fetched (i.e.  value of 2 means that the forecast is fetched every second hour?

Version is 0.91

**Comment by inspired-technologies** [comment]
Thanks, Jan, for reaching out.

OpenWeather (likewise other weather services) allow for hourly forecast data - ie. with the current 3.0 OneCall API 48hours. If internet is available this data is automatically fetched every _60mins_ for the current position; however, you can limit the amount of data used for computation down to eg. only 24h using the **horizon**  parameter. 

By design, in addition to optionally publishing _current_ as _outside.*_ we only publish 1 data set out of the specified range underneith _forecast.*_ - within the V2 api version of SignalK there are activities underway to have broader sets of data stored as resources - hence, we may adopt this accordingly in an upcoming release.

The **offset** parameter is used to select which one gets published. Enter a number between 0 and 47 (h) which suits your situation best - less than 3 (h) recommended when the vessel is underway to have the forecast making sense, but - of course - can be changed when used in a fixed station or staying moored or anchored for a longer period of time. Finally, _environment.forecast.time_ indeed represents the utc time the data is published for.

Hope that helps, otherwise let us know.
